name: Fetch Upstream

on: pull_request

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Upstream
      uses: bdougie/fetch-upstream@master
      with:
        upstream: https://github.com/LootLocker/unity-sdk.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
